### ISSUE TITLE
submit to CRAN

### ISSUE THREAD

**Issue by beanumber** [baumer-lab/fec16#20]

**Comment by mariumtapal** [comment]
Should we do this?

**Comment by beanumber** [comment]
What is the status of #22 ? If that is completed, we should close that issue. 

You can start the process by running `devtools::release()`. Please follow all the steps as best you can. Be patient -- it will take some time. When you get to the end, let me know.

**Comment by beanumber** [comment]
OK, great. Thanks @mariumtapal . Go for it!

**Comment by mariumtapal** [comment]
@beanumber we can close this
