### ISSUE TITLE
control output from read_all_*() functions

### ISSUE THREAD

**Issue by beanumber** [baumer-lab/fec16#22]
I don't have this quite right, but I think playing with this could work:

```{r}
withr::local_options(list(usethis.quiet = TRUE))
```

Please see my attempt at `read_all_contributions()` and see if you can get it to work in the vignette.

**Comment by mariumtapal** [comment]
Is there any important purpose of this? 
`cat(msg[-2], sep = "\n")`

I have gotten the function to work as we wanted it to, by only removing the `msg` variable:
```
if (!verbose) {
    invisible(utils::capture.output(
        dir <- usethis::use_zip(
          "https://www.fec.gov/files/bulk-downloads/2016/pas216.zip",
          destdir = tempdir(), cleanup = TRUE
        )
      )
    )
  } else {
    dir <- usethis::use_zip(
      "https://www.fec.gov/files/bulk-downloads/2016/pas216.zip",
      destdir = tempdir(), cleanup = TRUE
    )
  }
```

**Comment by mariumtapal** [comment]
We can close this!
