### ISSUE TITLE
CRAN error

### ISSUE THREAD

**Issue by mariumtapal** [baumer-lab/fec16#29]
Hi @beanumber, I got an email from CRAN to update fec16 before 28/8 to fix the warnings here:
[https://cran.r-project.org/web/checks/check_results_fec16.html](https://cran.r-project.org/web/checks/check_results_fec16.html)
``` 
Error: processing vignette 'fec_vignette.Rmd' failed with diagnostics:
    r_vector
    --- failed re-building ‘fec_vignette.Rmd’ 
```
I can't find anything to help me with the above r_vector diagnostic. A solution I can think of is removing the vignette from CRAN and just hosting it on GitHub.

**Comment by beanumber** [comment]
No, you don't want to remove the vignette, you just need to fix the offending bit of code. 

It says:

```
Quitting from lines 161-171 (fec_vignette.Rmd)
    Error: processing vignette 'fec_vignette.Rmd' failed with diagnostics:
    r_vector
```

Is that downloading a big file? You don't want to do that in the vignette. The vignette should compile very quickly. 

I'd recommend removing any large computation from the vignette.

**Comment by mariumtapal** [comment]
@beanumber yes, it is a calling the `read_all_contributions` function (~16MB) so it does take a little time to compile. I'll update the vignette so that this function isn't `eval`uated!

**Comment by mariumtapal** [comment]
@beanumber issue fixed and v0.1.1 is on its way to CRAN!

**Comment by beanumber** [comment]
Nice work, @mariumtapal ! What was the problem?

**Comment by mariumtapal** [comment]
@beanumber I fixed the vignette to compile faster but as you saw above, I still got an error on rhub Fedora Linux. I ran the rhub check a few days later again, and there was no error anymore. Not sure what happened there
