### ISSUE TITLE
fec16 dm object + visualisation

### ISSUE THREAD

**Issue by mariumtapal** [baumer-lab/fec16#39]
@beanumber As we talked a while ago, I have created a visualisation between the datasets in `fec16` using the `dm` package. What do we want to do next?

**Comment by beanumber** [comment]
Can you send a PR with this? 

* the script to generate the ER diagram should go in `data-raw/`, or it could be a function in the package
* the diagram itself should go in `inst/` and be shown on the README.

**Comment by beanumber** [comment]
This is so cool!

I hear what you are saying about the states, but I think it looks OK with them and I think the completeness is important. 

Is there a way to save the image automatically? Maybe using `webshot::webshot()` would work at the end of the `dm` script.

**Comment by mariumtapal** [comment]
@beanumber got it! I'll look into it and send another PR
