### ISSUE TITLE
usethis package dependency

### ISSUE THREAD

**Issue by rudeboybert** [baumer-lab/fec16#44]
In order for `read_all_contributions()` to work the user needs to have `usethis` installed. might be a good idea to make this an `fec16` dependency

**Comment by mariumtapal** [comment]
@beanumber I have moved `usethis` to imports since you can't use any of the functions that retrieve data without it.  The `if (require(usethis))` solution would be used 8 times across 4 functions if implemented instead.

**Comment by beanumber** [comment]
closed via #49
