### ISSUE TITLE
Documentation for results data frame

### ISSUE THREAD

**Issue by rudeboybert** [baumer-lab/fec16#46]
When running:
```
library(fec16)
?results_president
```
You get a single help file for `results_house1`, `results_senate`, `results_president`. However the list of variables in Format documents variables for the union of these three data frames; it might worth adding a note that while some datasets have some of these variables in common, not all variables necessarily exist in all 3 data frames

**Comment by mariumtapal** [comment]
Created new help files for all 3 datasets with `@seealso` tags to the other 2.

**Comment by beanumber** [comment]
closed via #49
