### ISSUE TITLE
expenditures data set

### ISSUE THREAD

**Issue by rudeboybert** [baumer-lab/fec16#47]
`read_all_expenditures()` is causing many computers to crash, which is understandable given the 52.1MB size of the data as indicated in the README. Given this is makes sense to only use the 1000 sample rows provided in the default `expenditures` data frame.

However for all the data frames that are loaded via `read_all_X()`, it would be good if in the `?expenditures` help file it indicated:
* not just `Operating expenditure information for a simple random sample of 1000 entries`
* rather `Operating expenditure information for a simple random sample of 1000 entries *out of X*`

Side note: this would be a good stats question about inferring about the total expenditure amount given the random sample

**Comment by mariumtapal** [comment]
Addressed!
